apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spot-autoscale
  region: eu-west-1

fargateProfiles:
  - name: fargate-default
    selectors:
      - namespace: default
        labels:
          compute-engine: fargate