apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spot-autoscale
  region: eu-west-1
  version: "1.15"
nodeGroups:
  - name: ng-spot-autoscale
    desiredCapacity: 1
    maxSize: 10
    instancesDistribution:
      instanceTypes: ["t3.large", "t2.large", "m5.large"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    availabilityZones: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
    iam:
      withAddonPolicies:
        autoScaler: true
        certManager: true
    labels:
      instance-type: spot
    ssh:
      publicKeyName: eks-tutorial-keypair

availabilityZones: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]